default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PG_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("PG_PASSWORD") { 1 } %>
  host: <%= ENV.fetch("PG_HOST") { "localhost" } %>
  port: <%= ENV.fetch("PG_PORT") { 5432 } %>

development:
  <<: *default
  database: bento

test:
  <<: *default
  database: bento

production:
  <<: *default
  database: bento
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>
